name: Bug — Rapport d’anomalie
description: Signaler un bug reproductible (UI, API, auth, DB, déploiement).
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Résumé
      description: Décris le problème en 1–3 phrases.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Étapes pour reproduire
      description: Liste des étapes précises.
      placeholder: |
        1. …
        2. …
        3. …
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Résultat attendu
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Résultat obtenu
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / Erreurs
      description: Colle le log/stacktrace (en masquant les secrets).
      render: shell
    validations:
      required: false
  - type: input
    id: env
    attributes:
      label: Environnement
      description: Local / Coolify / prod, OS, version Node, etc.
      placeholder: "Coolify + Postgres, Node 22, Next 14.2.33"
    validations:
      required: false

