name: Feature — Demande d’amélioration
description: Proposer une fonctionnalité/évolution.
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problème / besoin
      description: Qu’est-ce qui manque ? Pourquoi ?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposition
      description: Ce que tu veux exactement (UX, API, règles).
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Critères d’acceptation
      placeholder: |
        - [ ] …
        - [ ] …
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes / références
    validations:
      required: false

